#include "mpx/io.h"
#include "sys_req.h"
#include <alarms.h>
#include <pcb.h>
#include <context_switch.h>
#include <comhand.h>
#include <time.h>

// global variable for message and time
char* global_message = NULL;
char* global_time =NULL;

// global variable for message and time
char* global_message = NULL;
char* global_time =NULL;

void alarm(char *formatted_time, char* message, char* message)
{

    if(isValidTimeFormat(formatted_time) != 1)
    {
        //sys_req(WRITE, COM1, command, 9);
        sys_req(WRITE, COM1, "ERR: Invalid time format | use 'help' command\n", 46);
        return;
    }

    if(!pcb_find("alarm0"))
    {
        // set global message & time to generated by user
        global_message = message;
        global_time = formatted_time;

        /* create a ready, non-suspended process that is idle */
        create_pcb("alarm0", 0, 2);
            struct pcb* alarm0_pcb = pcb_find("alarm0");
            struct context* context_alarm0 = (struct context*)(((int)alarm0_pcb->process_ptr->stack_ptr)-sizeof(struct context) - sizeof(int));
            alarm0_pcb->process_ptr->stack_ptr = context_alarm0;

            /* set context for segment process */
            context_alarm0->CS = 0x08;
            context_alarm0->DS = 0x10;
            context_alarm0->ES = 0x10;
            context_alarm0->FS = 0x10;
            context_alarm0->GS = 0x10;
            context_alarm0->SS = 0x10;

            // EPB set to bottom of stack
            context_alarm0->EBP = (int)(alarm0_pcb->process_ptr->pcb_stack + PCB_STACK_SIZE - sizeof(struct context)) - sizeof(int);
            
            // ESP set to top of stack
            context_alarm0->ESP = (int)(alarm0_pcb->process_ptr->pcb_stack + PCB_STACK_SIZE - sizeof(struct context)) - sizeof(int);
            
            // EIP point to function proc1
            context_alarm0->EIP = (int)print_message;
            
            /* all other registers */
            context_alarm0->EAX = 0;
            context_alarm0->EBX = 0;
            context_alarm0->ECX = 0;
            context_alarm0->EDX = 0;
            context_alarm0->ESI = 0;
            context_alarm0->EDI = 0;

            // set EFLAGS
            context_alarm0->EFLAGS = 0x0202;

    } else if(!pcb_find("alarm1"))
    {
        // set global message & time to generated by user
        global_message = message;
        global_time = formatted_time;

        /* create a ready, non-suspended process that is idle */
        create_pcb("alarm1", 0, 2);
            struct pcb* alarm1_pcb = pcb_find("alarm1");
            struct context* context_alarm1 = (struct context*)(((int)alarm1_pcb->process_ptr->stack_ptr)-sizeof(struct context) - sizeof(int));
            alarm1_pcb->process_ptr->stack_ptr = context_alarm1;

            /* set context for segment process */
            context_alarm1->CS = 0x08;
            context_alarm1->DS = 0x10;
            context_alarm1->ES = 0x10;
            context_alarm1->FS = 0x10;
            context_alarm1->GS = 0x10;
            context_alarm1->SS = 0x10;

            // EPB set to bottom of stack
            context_alarm1->EBP = (int)(alarm1_pcb->process_ptr->pcb_stack + PCB_STACK_SIZE - sizeof(struct context)) - sizeof(int);
            
            // ESP set to top of stack
            context_alarm1->ESP = (int)(alarm1_pcb->process_ptr->pcb_stack + PCB_STACK_SIZE - sizeof(struct context)) - sizeof(int);
            
            // EIP point to function proc1
            context_alarm1->EIP = (int)print_message;
            
            /* all other registers */
            context_alarm1->EAX = 0;
            context_alarm1->EBX = 0;
            context_alarm1->ECX = 0;
            context_alarm1->EDX = 0;
            context_alarm1->ESI = 0;
            context_alarm1->EDI = 0;

        // set EFLAGS
        context_alarm1->EFLAGS = 0x0202;

    // Convert to integer
    int hh = atoi(formatted_time);
    int mm = atoi(formatted_time + 3);
    int ss = atoi(formatted_time + 6);

    // Convert to hexadecimal
    uint8_t hexHH = decToHex(hh);
    uint8_t hexMM = decToHex(mm);
    uint8_t hexSS = decToHex(ss);

    // once time is in hex, need to check for that time on computer
    // Read hours
    outb(0x70, 0x04);
    unsigned char hour = inb(0x71);

    // Read minutes
    outb(0x70, 0x02);
    unsigned char min = inb(0x71);

    // Read seconds
    outb(0x70, 0x00);
    unsigned char sec = inb(0x71);

    /* compare time on computer with formatted time given by user */
    if(hexHH == hour) // same hour, check for minutes
    {
        if(hexMM == min) // same minute, check seconds
        {
            if(hexSS == sec) // same sec, set EAX to exit to dispatch
            {
                sys_req(EXIT);
            } else if (hexSS < sec) { // past run time, set EAX to exit
                sys_req(EXIT);
            } else { // hexSS > sec - in this case we do not want to make alarm run
                // DO NOTHING
            }
        } else if (hexMM < min) { // past run time, so set EAX to exit to dispatch
            sys_req(EXIT);
        } else { // hexMM > min - in this case we do not want to make alarm run
            // DO NOTHING
        }
    } else if (hexHH < hour) { // past run time, set EAX to exit
        sys_req(EXIT);
    } else {
        // DO NOTHING
    }

}

void message_(char* message_from_user)
{
    print(message_from_user);
}

